- name: Install helm via snap
  shell: snap install helm --classic
  register: helm_result

- name: Add prometheus helm repo
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Add Helm repo stable
  shell: helm repo add stable https://charts.helm.sh/stable

- name: Add grafana helm repo
  shell: helm repo add grafana https://grafana.github.io/helm-charts

- name: Helm update
  shell: helm repo update

- name: Create monitoring namespace
  shell: kubectl create ns monitoring